### ISSUE TITLE
Theme | Background is not being applied

### ISSUE THREAD

**Issue by louisgv** [FormidableLabs/react-live#139]
> Version:     "react-live": "^2.0.1",

Codesandbox: https://codesandbox.io/s/k579vzppj7

# Expected:

The background of the LiveEditor to be "#282A36"

# Current result:

Background is white

**Comment by carrickjason** [comment]
I also noticed this when trying to use the nightOwl theme exported by prism-react-renderer.

**Comment by peduarte** [comment]
![](https://media1.giphy.com/media/l1KvQsIfNt9wRStWw/200w.gif?cid=5a38a5a25cd1cc4c626c31614df03cb3&rid=200w.gif)

**Comment by peduarte** [comment]
Can someone recommend a workaround for this?

**Comment by kiraarghy** [comment]
Hey everyone, I'm going to be having a look at this, this afternoon. 

For the moment you should be able to manually style the background of the editor as the following [example](https://codesandbox.io/s/vn40202rv3) ?

**Comment by peduarte** [comment]
@kiraarghy Nice oneeee <3

**Comment by kiraarghy** [comment]
Hey all I've just tested @louisgv's example on @VirtualDOMinic's branch with the background fix and it's looking good:

<img width="455" alt="Screenshot 2019-05-14 at 10 49 02" src="https://user-images.githubusercontent.com/21056165/57689025-a92b2780-7636-11e9-97c8-71e4f814e8cb.png">

Hopefully we should have it merged and a minor version going out soon, will keep you updated!

**Comment by peduarte** [comment]
Nice one, thanks @kiraarghy

**Comment by skawaguchi** [comment]
I forked @kiraarghy's version and used 2.1.0 and it looks like there's an error with the code. It's expecting `theme`, but whether it's provided to `LiveProvider` or `LiveEditor` directly, it's breaking: https://codesandbox.io/s/pensive-morning-g9n3e

I'm not sure if this is a new issue or not, but it seemed relevant to the conversation.

**Comment by sofiapoh** [comment]
This should be fixed now! https://github.com/FormidableLabs/react-live/commit/458acfda5ebe777a7d82c13da40f2450779b93e1

**Comment by skawaguchi** [comment]
@sofiapoh thanks for the quick turnaround. Just for the record, the `theme` bug is resolved, but the main issue still stands. I just defined the background with an inline style for now.

**Comment by sofiapoh** [comment]
If you pass a theme as prop do you still get this issue?
