### ISSUE TITLE
Caret position not working as expected

### ISSUE THREAD

**Issue by TeutaK** [FormidableLabs/react-live#343]
Hi there,

I am using the react-live editor, but I have a bad experience while typing code.
When I enter a new line after writing some code, the caret position backs to one line up. It is a bad UX for the end user.
Here is a demo of my issue: 

https://user-images.githubusercontent.com/16033100/228184546-01c6b1ac-8551-4364-a392-6190e614f2f8.mov

Any help would be very appreciated!
Thanks in advance!

**Comment by mo-sharif** [comment]
I am having the same issue above😢

**Comment by mryechkin** [comment]
This is a duplicate of #308.

This issue has been around for awhile now. For what its worth, I've been using [react-live-runner](https://www.npmjs.com/package/react-live-runner) instead and it has been working well. Carriage return works as expected there.

**Comment by mo-sharif** [comment]
thanks! react-live-runner looks like a great alternative 👍

**Comment by carloskelly13** [comment]
Thanks for the bug report here, we'll look at getting this fixed up. I can also recreate this bad UX with the carriage return.

**Comment by carloskelly13** [comment]
This should be fixed in 4.1.1.

**Comment by mryechkin** [comment]
> This should be fixed in 4.1.1.

Still happening for me unfortunately :(

**Comment by elchininet** [comment]
@carloskelly13,
This issue is not solved, as well as [this one](https://github.com/FormidableLabs/react-live/issues/308).
Just take two  minutes of your time and try to code in one of the windows of the demo, you will quickly notice the bad experience.
Regards

**Comment by carloskelly13** [comment]
Hi :wave: We saw another bug and got it patched up in 4.1.2, please see the video below, if there are continued issues, please open another one with some recreation steps. Thanks!

https://github.com/FormidableLabs/react-live/assets/1738349/bd57bdd6-0be5-49b9-85a2-3c122edbb459

**Comment by elchininet** [comment]
@carloskelly13,

It is easy to reproduce, just follow these steps:

* Go to [the demo](https://react-live.netlify.app/)
* Go to the second example and place your caret between the first and second parenthesis
* Hit enter
* Hit `backspace`

https://github.com/FormidableLabs/react-live/assets/3728220/b0537528-f1d3-4215-a316-61c3c95fc3d2

[As I mentioned before](https://github.com/FormidableLabs/react-live/issues/308#issuecomment-1078418397), this could be easily fixed if `use-editable` [is replaced in favour of react-simple-code-editor again](https://github.com/FormidableLabs/react-live/commit/2265d8dbca01631486f89de3b50753ead160d41c), the bug [is coming from there](https://github.com/FormidableLabs/use-editable/issues/17). I was using a patched version of the library that reverted that change without issues.

Maybe someone else want to open another issue, [this has taken more than one year for me](https://github.com/FormidableLabs/react-live/issues/308) so I migrated to [react-live-runner](https://www.npmjs.com/package/react-live-runner).

Regards

**Comment by elchininet** [comment]
Copied and pasted the code there

https://github.com/FormidableLabs/react-live/assets/3728220/7963d03e-6e88-4c5e-8a43-71f30a81c5cb

Just an advice, you should consider using `react-simple-code-editor` which is solid meanwhile you fix `use-editable` [which has a lot of bugs related to carriage return]([react-simple-code-editor again](https://github.com/FormidableLabs/react-live/commit/2265d8dbca01631486f89de3b50753ead160d41c)).

**Comment by mryechkin** [comment]
`4.1.2` looks to have fixed the carriage return issue with new line, but I now get an issue with it going back one character on the same line:

https://github.com/FormidableLabs/react-live/assets/5657181/5ce551be-e681-48dd-b242-76103fbd23fe

I'm going to echo @elchininet's sentiment about `use-editable` - these issues started happening ever since it was added.
